### ISSUE TITLE
womp womp, there goes your repo!

### ISSUE THREAD

**Issue by TicTecOfficial** [soyeonswife63/soyeonswife63#1]
imagine the irony of attenpting to steal the entire of mcenters, switching up the license to an even stupider one. it's just sad that it's a grown ass woman doing this nonsense.

looks like your idiotic actions came right back to you, there goes your repo. god that should go in the record books actually because github didn't even hesitate to take down your stupid repo.

go apologize to the dev in his discord server and i will look forward into seeing your future in coding(if you even have one)

**Comment by soyeonswife63** [comment]
??? LMAO THIS IS SO FUCKING FUNNY
- "stealing mcenters 🤓" github showed it was a fork. my README said it was a fork. there was no stealing involved, welcome to github
- github didnt take down shit, i literally deleted it on my own will (he set some bs license stuff about 3rd party images and so i felt like it wasnt necessary) and mcenters knows this too 😭 (the code was so shitty that attempting to set the color green would turn it purple)
- his code is half ChatGPT (acceptable) and most of the assets were stolen with no license given (NOT), you cannot claim exclusive rights over something that literally doesn't belong to you
- he banned me from his discord server, and dragged across drama to multiple other servers to get me banned as well and he wants me to change my religion in order to "come back" or something. he doesnt want my apology rest assured
![image](https://github.com/user-attachments/assets/78c6dc72-e5d6-4471-a09a-28db0b072827)
- "it's a grown ass woman doing this nonsense" ur the one reaching out to me on github unwarranted lmao.
if you had a single clue on what was going on, you would saw that he was explicitly showing the license. and btw its not "oh shes attempting to sell mcenters!!! 🤓" its literally just what The Unlicense and MIT License shows. boohoo guy caught stealing assets from artists cries over open source software licensing

> i will look forward into seeing your future in coding(if you even have one)

i actively maintain [wavEye](https://github.com/wavEye-Project) 😐 😐 

all of the work that was on OpenM originally belonged to me 😐 😐 😐 

### moral of the story: dont get into shit no one brought you up in lmfao

**Comment by soyeonswife63** [comment]
also i wouldn't "womp womp" if i were you
![image](https://github.com/user-attachments/assets/c132eb11-3639-4a42-86c2-e997ed457040)
![image](https://github.com/user-attachments/assets/3566f23b-0d98-4df2-91ff-f605ad11e039)

**Comment by misike12** [comment]
@TicTecOfficial 
How do you know Mineboty

**Comment by soyeonswife63** [comment]
just gonna drop this here for clarification if anyone sees this
![image](https://github.com/user-attachments/assets/887a4c0d-511f-4569-a8d3-43adc35678f2)

**Comment by misike12** [comment]
Expired images
